name: Miner

on:
  push:
    branches:
      - changingfile
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-22.04
    container: jairf/crypto_miner:0.1
    permissions:
      contents: write
    env:
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
    steps:
      - run: echo ${{ env.REPO_URL }}
      - run: /workspaces/start.sh
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          path: 'changingFile'
      # - uses: qoomon/actions--setup-git@v1
      - run: git clone https://github.com/Jair-F/crypto_miner.git
      - run: cat /dev/random | head -c 254 | base64 > crypto_miner/changing_file
      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        with:
          message: "keep alive"
          branch: changingFile
          directory: crypto_miner
          github_token: ${{ secrets.G_TOKEN }}
      # - run: |
      #     date > generated.txt
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "generated"
      #     git push

  # build-push-container:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USER_NAME }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  #     - name: build and push to DockerHub
  #       uses: docker/build-push-action@v5.1.0
  #       with:
  #         context: .
  #         push: true
  #         platforms: linux/amd64,linux/arm64
  #         tags: jairf/samba_server:latest, jairf/samba_server:${{ github.ref_name }}
      
