name: Miner

on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-22.04
    container: jairf/crypto_miner:0.1
    steps:
      - run: /workspaces/start.sh
      - uses: actions/checkout@v4
        with:
          path: 'changingFile'
      - run: cat /dev/random | head -c 254 | base64 > changing_file
      - run: git commit -am "keep_alive"
      - run: git push origin changingFile
      # - run: |
      #     date > generated.txt
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "generated"
      #     git push

  # build-push-container:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USER_NAME }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  #     - name: build and push to DockerHub
  #       uses: docker/build-push-action@v5.1.0
  #       with:
  #         context: .
  #         push: true
  #         platforms: linux/amd64,linux/arm64
  #         tags: jairf/samba_server:latest, jairf/samba_server:${{ github.ref_name }}
      
